### ISSUE TITLE
指摘事項10 SQLのパフォーマンス問題(2-1) (再) 

### ISSUE THREAD

**Issue by TakamasaSugiura** [swatanabe214/study_marking_201503#10]
1時間待っても処理が返ってきませんでした。

![kyoiku_011](https://cloud.githubusercontent.com/assets/7827645/8309163/da4caf52-1a03-11e5-8bce-ed3016bc3e56.jpg)

関連 #4

@a39a245ffa75727e4bd371a1eb71d3db63252d19

**Comment by swatanabe214** [comment]
私の環境では、25秒前後でした…。
1週間、試行錯誤しましたが現状SQLが一番速かったです。
どのように修正すると、パフォーマンスが良くなるでしょうか。

![image](https://cloud.githubusercontent.com/assets/8566307/8476395/deaaccf6-20fb-11e5-8dc1-e5137114052b.png)

**Comment by TakamasaSugiura** [comment]
確認しました。
残念ですが、これだと、 #8 の不具合を再発させてしまいます。
@4ee66ae0554353a7999ecbf2c6302fa048b94580

**Comment by TakamasaSugiura** [comment]
確認しました。

@ea410f9eef4671c35472986313126ed887260644
